- name: Combine systemd_services with default values
  set_fact:
    _item: "{{ systemd_services_default | combine(item) }}"

- name: Assert systemd service type is fine
  assert:
    that:
      - _item.type in ["simple","notify","oneshot","forking"]

- name: Generate systemd service files
  template:
    src:  systemd.service
    dest: "/etc/systemd/system/{{ _item.name }}"
    mode: "0600"
  notify: Reload systemd daemon

- name: Start/stop systemd service
  service:
    name:    "{{ _item.name    }}"
    state:   "{{ _item.state   }}"
    enabled: "{{ _item.enabled }}"
  when: not ansible_check_mode
