- name: Combine systemd_services with default values
  set_fact:
    _item: "{{ systemd_services_default | combine(item) }}"

- name: Assert systemd service type is fine
  assert:
    that:
      - _item.type in ["simple","notify","oneshot","forking"]

- name: Generate systemd service files
  template:
    src:  systemd.service
    dest: "/etc/systemd/system/{{ _item.name }}.service"
    mode: "0600"
  notify: Reload systemd daemon

- name: Flush handlers to discover the service
  meta: flush_handlers

- name: Start/stop systemd service
  service:
    name:    "{{ _item.name }}.service"
    state:   "{{ omit if not _item.state else _item.state  }}"   # omit if state is false else apply state value
    enabled: "{{ _item.enabled }}"
  when: not ansible_check_mode
