- name: Combine systemd_services with default values
  set_fact:
    _item: "{{ systemd_services_default | combine(item) }}"

- name: Assert systemd service type is fine
  assert:
    that: _item.type in ["simple","notify","oneshot","forking"]

- debug:
    var: _item

- name: Generate systemd service files
  template:
    src:  systemd.service
    dest: "/etc/systemd/system/{{ _item.name }}"
    mode: "0600"

# - name: Manage systemd service
#   service:
#     name:    httpd
#     state:   started
#     enabled: true
